name: CI-CD Shadow App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build PRODUCT SERVICE
      - name: Set up JDK 17 for product-service
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build product-service
        run: |
          cd lain_confort-main/back-end1/product-service
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      # Build ORDER SERVICE
      - name: Build order-service
        run: |
          cd lain_confort-main/back-end2/order-Service
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      # Build Angular
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install front dependencies
        run: |
          cd lain_confort-main/front-end
          npm install

      - name: Build Angular frontend
        run: |
          cd lain_confort-main/front-end
          npm run build --prod

      # Upload Angular build
      - name: Upload Angular build
        uses: actions/upload-artifact@v3
        with:
          name: dist-build
          path: lain_confort-main/front-end/dist/

      # Deploy via SSH
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 4.211.255.55
          username: firas
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "==== CLEANING old /var/www/html ===="
            sudo rm -rf /var/www/html/*

            echo "==== DOWNLOAD latest ANGULAR build ===="
            curl -L -o dist.zip https://github.com/${{ github.repository }}/releases/latest/download/dist-build.zip

            echo "==== UNZIP build into /var/www/html ===="
            sudo unzip -o dist.zip -d /var/www/html/

            echo "==== RESTART NGINX ===="
            sudo systemctl restart nginx
omfort/lain_confort-main/front-end/dist/* /var/www/html/
            sudo systemctl restart nginx
