name: CI-CD Shadow App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      ###############################################
      # Build PRODUCT-SERVICE (Spring Boot)
      ###############################################
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build product-service
        run: |
          cd lain_confort-main/back-end1/product-service
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      ###############################################
      # Build ORDER-SERVICE
      ###############################################
      - name: Build order-service
        run: |
          cd lain_confort-main/back-end2/order-Service
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      ###############################################
      # Build Angular Front-End
      ###############################################
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install front dependencies
        run: |
          cd lain_confort-main/front-end
          npm install

      - name: Build Angular
        run: |
          cd lain_confort-main/front-end
          npm run build --prod

      ###############################################
      # DEPLOY TO VM SSH
      ###############################################
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/laincomfort
            sudo rm -rf *
            git clone https://github.com/firasrhouma/shadow-app.git .
            
            sudo cp -r lain_confort-main/front-end/dist/* /var/www/html/
            sudo systemctl restart nginx
